apiVersion: v1
kind: Secret
metadata:
  name: app-credentials
  namespace: {{ include "kikplate.namespace" . }}
  labels:
    {{- include "kikplate.labels" . | nindent 4 }}
type: Opaque
stringData:
  JWT_SECRET: {{ .Values.secrets.jwtSecret | quote }}
  GITHUB_TOKEN: {{ .Values.secrets.github.token | quote }}
  GITHUB_APP_PRIVATE_KEY: {{ .Values.secrets.github.appPrivateKey | quote }}
  GITHUB_APP_WEBHOOK_SECRET: {{ .Values.secrets.github.appWebhookSecret | quote }}
  SSO_GITHUB_CLIENT_SECRET: {{ .Values.secrets.sso.githubClientSecret | quote }}
  SSO_GOOGLE_CLIENT_SECRET: {{ .Values.secrets.sso.googleClientSecret | quote }}
  SSO_GITLAB_CLIENT_SECRET: {{ .Values.secrets.sso.gitlabClientSecret | quote }}
